# Quantum Computing (บทที่ 1)

การคำนวณเชิงควอนตัม (Quantum Computing) คือ การใช้คุณสมบัติจาก กลศาสตร์ควอนตัม (Quantum Machanic) เช่น superposition, entanglement, quantum tunneling เพื่อเพิ่มประสิทธิภาพในการคำนวณ ซึ่งลดเวลาในการคำนวณจากคอมพิวเตอร์ปกติอย่างมาก

การคำนวณเชิงควอนตัมจะใช้ สถานะทางควอนตัน (Quantum states) ที่แสดงด้วย เวคเตอร์ของจำนวนเชิงซ้อน (Complex vecotr) เพื่อการคำนวณแทนที่จะใช้ เลขฐานสอง (Binary number) เหมือนคอนพิวเตอร์ปกติ

## 1.1 The qubit

คิวบิต (qubit) ย่อมาจาก ควอนตัมบิต (Quantum bit) ซึ่งเป็นตัวแทน สถานะทางควอนตัม สามารถเขียนให้อยู่ในรูป เวคเตอร์ของจำนวนเชิงซ้อน 2 มิติ ซึ่งจะเรียกว่า สถานะ 1 คิวบิต (Single qubit state) นิยามได้ดังนี้

$$\lvert\phi\rangle = \alpha\lvert 0\rangle + \beta\lvert 1\rangle$$

โดยที่ $\alpha, \beta$ เป็นจำนวนเชิงซ้อน (Complex number) ซึ่ง $|\alpha|^2 + |\beta|^2 = 1$ 

และ $\lvert 0\rangle = \begin{bmatrix}1\\0\end{bmatrix}, \lvert 1\rangle = \begin{bmatrix}0\\1\end{bmatrix}$ (ถูกเรียกว่า ket 0, ket 1 ตามลำดับ)

เราจะสังเกตเห็นได้ว่า $\lvert\phi\rangle$ เป็นการผสมของสถานะ $\lvert 0\rangle, \lvert 1\rangle$ หรือ สถานะบิตสตริง (bit-string states)

และ $|\alpha|^2$ คือค่าความน่าจะเป็น ที่ $\phi$ จะคืนค่าสถานะเป็น $\lvert 0\rangle$ เมื่อ $\phi$ ถูกวัด (Measuring a qubit)

และ $|\beta|^2$ คือค่าความน่าจะเป็น ที่ $\phi$ จะคืนค่าสถานะเป็น $\lvert 1\rangle$  เมื่อ $\phi$ ถูกวัด (Measuring a qubit)

In [1]:
import numpy as np #lib สำหรับสร้าง เวคเตอร์และการคำนวณเชิงเวคเตอร์

In [2]:
#มาลองสร้าง qubit กัน

#สร้าง ket
ket_0 = np.array([[1], [0]])
ket_1 = np.array([[0], [1]])

#สร้าง alpha, beta
alpha = 1 / (2**0.5)
beta = 1 / (2**0.5)

In [3]:
#พิสูจน์ว่า  alpha ** 2 + beta ** 2 == 1
alpha ** 2 + beta ** 2

0.9999999999999998

In [4]:
#สร้าง qubit  phi
phi = alpha * ket_0 + beta * ket_1
print(phi)

[[0.70710678]
 [0.70710678]]


# 1.2 System of qubits

สถานะควอนตัม(Quantum states) ไดๆ เป็นเวคเตอร์มาตรฐาน (normalized vector) ในปริภูมิเชิงซ้อน (complex vector space) ทำให้ผลรวมความน่าจะเป็นของแต่ละสถานะมีผลรวมเท่ากับ $1$

ในควอนตัมคอมพิวเตอร์ (Quantum Computer) สามารถมีจำนวนคิวบิตได้มากกว่า $1$ เรียกว่า ระบบของคิวบิต (System of qubits) ซึ่งทำให้เกิดสถานะทางควอนตัมเพิ่มขึ้นมาเป็น $2^n$ เมื่อ $n$ เป็นจำนวนคิวบิตในระบบคิวบิต

เราสามารถสร้างสถานะทางควอนตัมของระบบคิวบิตที่มีสองคิวบิต โดยใช้ เทนเซอร์โปรดัคท์ (tensor product, $\otimes$) นิยามได้ดังนี้


ให้ $\lvert\phi\rangle = \begin{bmatrix}\alpha\\ \beta\end{bmatrix}$ และ
$\lvert\acute{\phi}\rangle = \begin{bmatrix}\acute{\alpha}\\ \acute{\beta}\end{bmatrix}$ แล้ว

$$\lvert\phi\rangle\otimes\lvert\acute{\phi}\rangle =  \begin{bmatrix}\alpha\\ \beta\end{bmatrix} \otimes\begin{bmatrix}\acute{\alpha}\\ \acute{\beta}\end{bmatrix} = \begin{bmatrix}\alpha\acute{\alpha}\\ \alpha\acute{\beta}\\ \beta\acute{\alpha}\\ \beta\acute{\beta}\end{bmatrix}$$

โดยทั่วไปเราสามารถเขียนเทนเซอร์โปรดัคท์ของสองคิวบิตแบบสั้นได้ดังนี้ $\lvert\phi\rangle\otimes\lvert\acute{\phi}\rangle = \lvert \phi\acute{\phi}\rangle$ ซึ่งการคำนวณเทนเซอร์โปรดัคท์ของ $2$ คิวบิตถูกเรียกว่า Kronecker product

ตัวอย่างโค้ด 
1. จงคำนวณ $\lvert 10 \rangle$
2. จงคำนวณ $\lvert 000 \rangle$

In [5]:
#ข้อ 1
np.kron(ket_0,ket_1)

array([[0],
       [1],
       [0],
       [0]])

In [6]:
#ข้อ 2
np.kron(np.kron(ket_0, ket_0), ket_0)

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

สถานะใหม่ของระบบของคิวบิตที่ถูกนิยามด้วยการคูณเทนเซอร์โปรดัคท์ของสถานะทั้งหมดในระบบ จะถูกเรียกว่า สถานะร่วม (joint state)

ตัวอย่างของ สถานะร่วม

กำหนดให้ $\lvert \gamma_j\rangle = \alpha_j\lvert 0\rangle + \beta_j \lvert 1\rangle$ สำหรับ $j = 1,2,3$ สถานะร่วมของสามคิวบิตนี้คือ

$\begin{align}\lvert \gamma_1\gamma_2\gamma_3\rangle &=
\lvert\gamma_1\rangle\otimes\lvert\gamma_2\rangle\otimes\lvert\gamma_3\rangle\\
&=\alpha_1\alpha_2\alpha_3\lvert 000\rangle+
\alpha_1\alpha_2\beta_3\lvert 001\rangle+
\alpha_1\beta_2\alpha_3\lvert 010\rangle+
\beta_1\alpha_2\alpha_3\lvert 100\rangle\\
&+\beta_1\beta_2\beta_3\lvert 111\rangle+
\beta_1\beta_2\alpha_3\lvert 110\rangle+
\beta_1\alpha_2\beta_3\lvert 101\rangle+
\alpha_1\beta_2\beta_3\lvert 011\rangle
\end{align}$

จะเห็นได้ว่า ระบบคิวบิตข้างต้นมี $3$ คิวบิตทำให้มีสถานะร่วม ซึ่งเกิดจากผลรวมของสถานะตามสมการทั้งหมด $2^3 = 8$ สถานะ โดยทั้ง $8$ สถานะเป็น เวคเตอร์ฐาน (basis vector) (กล่าวคือเป็นเวคเตอร์ขนาด 1 หน่วย(unit vector) และเวคเตอร์ทั้ง $8$ ตั้งฉากกัน (orthogonal)) เราจะเรียกสถานะทั้ง $8$ นี้เป็น สถานะฐาน (basis states)

และแต่ละสถานะมีค่าสัมประสิทธิ์ของตัวเอง ซึ่งนำผลรวมทั้งหมดของค่าสัมบูรณ์ของสัมประสิทธิ์ยกกำลังสองจะมีค่าเท่ากับ $1$ 

ตัวอย่างโค้ด 

3. กำหนดให้ $\lvert\phi\rangle = \frac{1}{\sqrt{2}}\lvert 0\rangle + \frac{1}{\sqrt{2}}\lvert 1\rangle$ จงคำนวณ $\lvert\phi 0 1\rangle$ และเช็คว่าผลรวมทั้งหมดของค่าสัมบูรณ์ของสัมประสิทธิ์ยกกำลังสองมีค่าเท่ากับ $1$ หรือไม่

In [7]:
#ข้อ 3
result = np.kron(np.kron(phi, ket_0), ket_1)

In [8]:
result

array([[0.        ],
       [0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.        ],
       [0.        ]])

In [9]:
np.abs(result) ** 2

array([[0. ],
       [0.5],
       [0. ],
       [0. ],
       [0. ],
       [0.5],
       [0. ],
       [0. ]])

In [10]:
sum(np.abs(result) ** 2)

array([1.])

# 1.3 Superposition and entanglement

จากบท 1.2 จะพบว่าเราสามารถสร้าง สถานะร่วม $n$ คิวบิต ได้โดยหาผลคูณเทนเซอร์โปรดัคท์ของ $n$ คิวบิต อย่างไรก็ตามจะมีบาง สถานะควอนตัม ซึ่งไม่สามารถเขียนแสดงให้อยู่ในรูปของผลคูณเทนเซอร์โปรดัคท์ของ $n$ คิวบิตได้ ซึ่งเราจะเรียกมันว่า สถานะพัวพัน(entangled states) ยกตัวอย่างเช่น

$$\lvert \Psi\rangle = \frac{1}{\sqrt{2}}(\lvert000\rangle + \lvert111\rangle)$$

การพัวพัน(Entanglement) สามารถสร้าง $2^n$ มิติในปริภูมิเชิงซ้อนโดยใช้เพียงจำนวน $n$ คิวบิตเพื่อให้เราใช้คำนวณในมัน ทำให้คอวนตัมคอมพิวเตอร์มีความสามารถบางอย่างมากกว่าคอมพิวเตอร์ทั่วไป

ตัวอย่างโค้ด 

4. จงสร้าง สถานะพัวพัน $\lvert \Psi\rangle = \frac{1}{\sqrt{2}}(\lvert000\rangle + \lvert111\rangle)$

In [11]:
Psi = 1/np.sqrt(2) * (np.kron(np.kron(ket_0, ket_0), ket_0) + np.kron(np.kron(ket_1, ket_1), ket_1))
print(Psi)

[[0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.70710678]]


# Inner and outer products
- สังยุคเชิงซ้อน (complex conjugte)

กำหนดให้ $\lvert\phi\rangle = \begin{bmatrix}\alpha\\ \beta\end{bmatrix}$ (ถูกเรียกว่า ket), จะได้ว่า   $\langle\phi\rvert = [\alpha^*\quad\beta^*]$ (ถูกเรียกว่า bra) โดย $^*$ คือการสังยุคเชิงซ้อน
- อินเนอร์โปรดัคท์ (Inner product) คือ การซ้อนทับ(overlaping) กันระหว่างสองสถานะควอนตัม

กำหนดให้ $\lvert\phi\rangle = \alpha\lvert0\rangle + \beta\lvert1\rangle$ และ $\lvert\psi\rangle = \gamma\lvert0\rangle + \delta\lvert1\rangle$ การทับซ้อนของสองสถานะคือ 

$$\langle\psi\lvert\phi\rangle =[\gamma^*\quad\delta^*]\begin{bmatrix}\alpha\\ \beta\end{bmatrix}= \gamma^*\alpha + \delta^*\beta$$

- เอาท์เตอร์โปรดัคท์ (outer product) เป็นการดำเนินการ(operation) ที่สำคัญตัวหนึ่งที่มีผลลัพธ์เป็นเมทริกซ์(Matrix)  

กำหนดให้ $\lvert\phi\rangle = \alpha\lvert0\rangle + \beta\lvert1\rangle$ และ $\lvert\psi\rangle = \gamma\lvert0\rangle + \delta\lvert1\rangle$ เอาท์เตอร์โปรดัคท์นิยามโดย 

$$\lvert\psi\rangle\langle\phi\rvert =\begin{bmatrix}\gamma\\ \delta\end{bmatrix}[\alpha^*\quad\beta^*]= \begin{bmatrix}\gamma\alpha^* & \gamma\beta^* \\ \delta\alpha^* &  \delta\beta^*\end{bmatrix}$$

นอกจากนี้ เมทริกซ์ไดๆ สามารถเขียนให้อยู่ในรูปผลรวมของการดำเนินการเอาท์เตอร์โปรดัคท์ได้

ยกตัวอย่างเช่น

$$A = \begin{bmatrix}A_{00} & A_{01}\\A_{10} &A_{11}\end{bmatrix} = 
A_{00}\lvert0\rangle\langle0\rvert+
A_{01}\lvert0\rangle\langle1\rvert+
A_{10}\lvert1\rangle\langle0\rvert+
A_{11}\lvert1\rangle\langle1\rvert
$$

การแปลงเมทริกซ์ให้อยู่ในรูปผลรวมของการดำเนินการเอาท์เตอร์โปรดัคท์ ทำให้เราสามารถทำการคูณเมทริกซ์กับสถานะควอนตัมได้ ดังแสดงในตัวอย่างนี้

$$\begin{align}
A\lvert\phi\rangle &= 
A_{00}\lvert0\rangle\langle0\rvert\phi\rangle+
A_{01}\lvert0\rangle\langle1\rvert\phi\rangle+
A_{10}\lvert1\rangle\langle0\rvert\phi\rangle+
A_{11}\lvert1\rangle\langle1\rvert\phi\rangle\\\\
&=
A_{00}\lvert0\rangle\alpha+
A_{01}\lvert0\rangle\beta+
A_{10}\lvert1\rangle\alpha+
A_{11}\lvert1\rangle\beta
\\\\
&=
\begin{bmatrix}
A_{00}\alpha + A_{01}\beta\\
A_{10}\alpha + A_{11}\beta|
\end{bmatrix}
\end{align}
$$

ตัวอย่างโค้ด

3. กำหนดให้ $\lvert\phi\rangle = \frac{1}{\sqrt{2}}\lvert 0\rangle + \frac{1}{\sqrt{2}}\lvert 1\rangle$ และ $H = \frac{1}{\sqrt{2}}\begin{bmatrix}1 & 1\\1 & -1\end{bmatrix}$ จงคำนวณ $H\lvert\phi\rangle$

In [12]:
H = 1/2**0.5 * np.array([[1, 1],
                         [1,-1]])

In [13]:
H @ phi

array([[1.],
       [0.]])

# Measurement

การวัด(Measurement) คือการแปลง ข้อมูลเชิงควอนตัม(Quantum information) ที่อยู่ในระบบควอนตัมซึ่งอยู่ในรูปเวคเตอร์ให้อยู่ในรูปของ ข้อมูลดั้งเดิม(Classical information) โดยมีผลลัพธ์เป็นความน่าจะเป็นว่า**สถานะควอนตัมที่สนใจ**จะกลายเป็น**สถานะที่ต้องการวัด**เท่าไดเมื่อถูกวัด

โดยวิธีการวัดเราจะใช้ อินเนอร์โปรดัคท์กับสถานะ 1 คิวบิต โดย
- ความน่าจะเป็นที่ สถานะ $\lvert\phi\rangle$ จะกลายเป็น $\lvert0\rangle$ เมื่อถูกวัด คือ $|\langle0\rvert\phi\rangle|^2$

- ความน่าจะเป็นที่ สถานะ $\lvert\phi\rangle$ จะกลายเป็น $\lvert1\rangle$ เมื่อถูกวัด คือ $|\langle1\rvert\phi\rangle|^2$

ดังนั้นการวัดความน่าจะเป็นสามารถแทนด้วย ค่าสัมบูรณ์กำลังสอง(squared absolute values) ของอินเนอร์โปรดัคท์