# Quantum Computing (บท 1)

การคำนวณเชิงควอนตัม (Quantum Computing) คือ การใช้คุณสมบัติจาก กลศาสตร์ควอนตัม (Quantum Machanic) เช่น superposition, entanglement, quantum tunneling เพื่อเพิ่มประสิทธิภาพในการคำนวณ ซึ่งลดเวลาในการคำนวณจากคอมพิวเตอร์ปกติอย่างมาก

การคำนวณเชิงควอนตัมจะใช้ สถานะทางควอนตัน (Quantum states) ที่แสดงด้วย เวคเตอร์ของจำนวนเชิงซ้อน (Complex vecotr) เพื่อการคำนวณแทนที่จะใช้ เลขฐานสอง (Binary number) เหมือนคอนพิวเตอร์ปกติ

## 1. The qubit

คิวบิต (qubit) ย่อมาจาก ควอนตัมบิต (Quantum bit) ซึ่งเป็นตัวแทน สถานะทางควอนตัม สามารถเขียนให้อยู่ในรูป เวคเตอร์ของจำนวนเชิงซ้อน 2 มิติ นิยามได้ดังนี้

$$\lvert\phi\rangle = \alpha\lvert 0\rangle + \beta\lvert 1\rangle$$

โดยที่ $\alpha, \beta$ เป็นจำนวนเชิงซ้อน (Complex number) ซึ่ง $|\alpha|^2 + |\beta|^2 = 1$ 

และ $\lvert 0\rangle = \begin{bmatrix}1\\0\end{bmatrix}, \lvert 1\rangle = \begin{bmatrix}0\\1\end{bmatrix}$ (ถูกเรียกว่า ket 0, ket 1 ตามลำดับ)

เราจะสังเกตเห็นได้ว่า $\lvert\phi\rangle$ เป็นการผสมของสถานะ $\lvert 0\rangle, \lvert 1\rangle$ 

และ $|\alpha|^2$ คือค่าความน่าจะเป็น ที่ $\phi$ จะคืนค่าสถานะเป็น $\lvert 0\rangle$ เมื่อ $\phi$ ถูกวัด (Measuring a qubit)

และ $|\beta|^2$ คือค่าความน่าจะเป็น ที่ $\phi$ จะคืนค่าสถานะเป็น $\lvert 1\rangle$  เมื่อ $\phi$ ถูกวัด (Measuring a qubit)

In [1]:
import numpy as np #lib สำหรับสร้าง เวคเตอร์และการคำนวณเชิงเวคเตอร์

In [2]:
#มาลองสร้าง qubit กัน

#สร้าง ket
ket_0 = np.array([[1], [0]])
ket_1 = np.array([[0], [1]])

#สร้าง alpha, beta
alpha = 1 / (2**0.5)
beta = 1 / (2**0.5)

In [3]:
#พิสูจน์ว่า  alpha ** 2 + beta ** 2 == 1
alpha ** 2 + beta ** 2

0.9999999999999998

In [4]:
#สร้าง qubit  phi
phi = alpha * ket_0 + beta * ket_1
print(phi)

[[0.70710678]
 [0.70710678]]


# 2. System of qubits

สถานะของระบบควอนตัมไดๆ เป็นเวคเตอร์มาตรฐาน (normalized vector) ในปริภูมิเชิงซ้อน (complex vector space) ทำให้ผลรวมความน่าจะเป็นของแต่ละสถานะมีผลรวมเท่ากับ $1$

ในควอนตัมคอมพิวเตอร์ (Quantum Computer) สามารถมีจำนวนคิวบิตได้มากกว่า $1$ เรียกว่า ระบบของคิวบิต (System of qubits) ซึ่งทำให้เกิดสถานะทางควอนตัมเพิ่มขึ้นมาเป็น $2^n$ เมื่อ $n$ เป็นจำนวนคิวบิตในระบบคิวบิต

เราสามารถสร้างสถานะทางควอนตัมของระบบคิวบิตที่มีสองคิวบิต โดยใช้ เทนเซอร์โปรดัคท์ (tensor product, $\otimes$) นิยามได้ดังนี้


ให้ $\lvert\phi\rangle = \begin{bmatrix}\alpha\\ \beta\end{bmatrix}$ และ
$\lvert\acute{\phi}\rangle = \begin{bmatrix}\acute{\alpha}\\ \acute{\beta}\end{bmatrix}$ แล้ว

$$\lvert\phi\rangle\otimes\lvert\acute{\phi}\rangle =  \begin{bmatrix}\alpha\\ \beta\end{bmatrix} \otimes\begin{bmatrix}\acute{\alpha}\\ \acute{\beta}\end{bmatrix} = \begin{bmatrix}\alpha\acute{\alpha}\\ \alpha\acute{\beta}\\ \beta\acute{\alpha}\\ \beta\acute{\beta}\end{bmatrix}$$

โดยทั่วไปเราสามารถเขียนเทนเซอร์โปรดัคท์ของสองคิวบิตแบบสั้นได้ดังนี้ $\lvert\phi\rangle\otimes\lvert\acute{\phi}\rangle = \lvert \phi\acute{\phi}\rangle$ ซึ่งการคำนวณเทนเซอร์โปรดัคท์ของ $2$ คิวบิตถูกเรียกว่า Kronecker product

ตัวอย่างโค้ด 
1. จงคำนวณ $\lvert 10 \rangle$
2. จงคำนวณ $\lvert 000 \rangle$

In [6]:
#ข้อ 1
np.kron(ket_0,ket_1)

array([[0],
       [1],
       [0],
       [0]])

In [12]:
#ข้อ 2
np.kron(np.kron(ket_0, ket_0), ket_0)

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

สถานะใหม่ของระบบของคิวบิตที่ถูกนิยามด้วยการคูณเทนเซอร์โปรดัคท์ของสถานะทั้งหมดในระบบ จะถูกเรียกว่า สถานะร่วม (joint state)

ตัวอย่างของ สถานะร่วม

กำหนดให้ $\lvert \gamma_j\rangle = \alpha_j\lvert 0\rangle + \beta_j \lvert 1\rangle$ สำหรับ $j = 1,2,3$ สถานะร่วมของสามคิวบิตนี้คือ

$\begin{align}\lvert \gamma_1\gamma_2\gamma_3\rangle &=
\lvert\gamma_1\rangle\otimes\lvert\gamma_2\rangle\otimes\lvert\gamma_3\rangle\\
&=\alpha_1\alpha_2\alpha_3\lvert 000\rangle+
\alpha_1\alpha_2\beta_3\lvert 001\rangle+
\alpha_1\beta_2\alpha_3\lvert 010\rangle+
\beta_1\alpha_2\alpha_3\lvert 100\rangle\\
&+\beta_1\beta_2\beta_3\lvert 111\rangle+
\beta_1\beta_2\alpha_3\lvert 110\rangle+
\beta_1\alpha_2\beta_3\lvert 101\rangle+
\alpha_1\beta_2\beta_3\lvert 011\rangle
\end{align}$

จะเห็นได้ว่า ระบบคิวบิตข้างต้นมี $3$ คิวบิตทำให้มีสถานะทั้งหมดคือ $2^3 = 8$ สถานะ

และแต่ละสถานะมีค่าความน่าจะเป็นของตัวเองตามสมการ

ตัวอย่างโค้ด 

3. กำหนดให้ $\lvert\phi\rangle = \frac{1}{\sqrt{2}}\lvert 0\rangle + \frac{1}{\sqrt{2}}\lvert 1\rangle$ จงคำนวณ $\lvert\phi 0 1\rangle$

In [13]:
#ข้อ 3
np.kron(np.kron(phi, ket_0), ket_1)

array([[0.        ],
       [0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.        ],
       [0.        ]])